version: '3'

services:
    web:
        container_name: fastapi
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - .:/app
        environment:
            - DATABASE_URL=postgresql://postgres:dbmaster@db:5432/postgres
        ports:
            - '8000:8000'
        networks:
            - dev-network
    db:
        container_name: fastapi-postgres
        image: postgres:15-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data
        expose:
            - 5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: dbmaster
            POSTGRES_DB: postgres
        networks:
            - dev-network
    pgadmin:
        container_name: fastapi-pgadmin
        image: dpage/pgadmin4:8.4
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin123
            PGADMIN_LISTEN_PORT: 5433
            PGADMIN_CONFIG_SERVER_MODE: 'False'
            PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
            PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: 'False'
        ports:
            - '5433:5433'
        depends_on:
            - db
        networks:
            - dev-network
volumes:
    postgres_data:
networks:
    dev-network: