version: '3'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        depends_on:
            - db
        volumes:
            - .:/app
        environment:
            - DATABASE_URL=postgresql://postgres:dbmaster@db:5432/postgres
        ports:
            - '8000:80'
    db:
        image: postgres:15-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data
        expose:
            - 5432
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: dbmaster
            POSTGRES_DB: postgres
volumes:
    postgres_data:
